### ISSUE TITLE
build.gradle.kts "No set method providing array access"

### ISSUE THREAD

**Issue by Vespertilo** [romangraef/Forge1.8.9Template#19]
I recently downloaded the template, and I got an error in the build.gradle.
<img width="616" alt="image" src="https://github.com/romangraef/Forge1.8.9Template/assets/65370729/64cda7e9-6128-44cb-a2f4-a70d88680637">
<img width="412" alt="image" src="https://github.com/romangraef/Forge1.8.9Template/assets/65370729/df805819-6084-4cef-97e2-3e38e6576564">

I can still run the Minecraft Client fine, but this is bugging me. Any ideas?

**Comment by romangraef** [comment]
Are you sure you downloaded the entire template? Please use the template as intended, by generating a repository and cloning it (or by using a zip file and then manually running ./make-my-own.sh). In either case, your IDE is probably wrong about this being an issue. If it is a real issue, please provide a log that is generated when doing a proper import, or one that is generated by `./gradlew build`.

**Comment by romangraef** [comment]
Closing because of lack of response. Please reopen with the requested information if you still need help.
