### ISSUE TITLE
runClient task fails

### ISSUE THREAD

**Issue by x123development** [romangraef/Forge1.8.9Template#5]
As stated in the title, when trying to execute the "loom>runClient" task everything compiles successfully and is successfully assembled into a jar, but upon launching the task fails with the following error:

>Task :runClient FAILED
4 actionable tasks: 3 executed, 1 up-to-date
Exception in thread "main" java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
	at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':runClient'.
> Process 'command 'C:\Program Files\Java\jdk-17.0.4.1\bin\java.exe'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 13s
3:37:30 PM: Execution finished 'runClient'.

I am using IntelliJ and have set the Gradle jdk to 17 and the project jdk to 1.8 as stated in the readme.
It seems, that the task tries to open Minecraft using the jdk 17 despite requiring jdk 1.8 to run. That is what I have found out, based on the Exception.

Running the mod with a fresh forge installation via the Minecraft launcher works fine. It's only the "runClient" task having issues.

I've attached the gradle config and build files as .txt here, in case that is important.

[settings.gradle.kts.txt](https://github.com/romangraef/Forge1.8.9Template/files/9591862/settings.gradle.kts.txt)
[gradle.properties.txt](https://github.com/romangraef/Forge1.8.9Template/files/9591863/gradle.properties.txt)
[build.gradle.kts.txt](https://github.com/romangraef/Forge1.8.9Template/files/9591864/build.gradle.kts.txt)

**Comment by romangraef** [comment]
The `runClient` task currently does not work with loom in general in older versions. Please use the `genIntellijRuns` task to generate a run configuration and run this configuration.

**Comment by x123development** [comment]
Thanks for the clarification. 
Works like a charm!
