### ISSUE TITLE
Obfuscation Path Missing?

### ISSUE THREAD

**Issue by tikaros** [romangraef/Forge1.8.9Template#7]
Is there a function to re-obfuscate the jar and replace original minecraft class names with the obfuscated ones? Like the reobfJar task in ForgeGradle

Like there:
![Screenshot_3](https://user-images.githubusercontent.com/55065837/201537762-476a1bad-d6c4-483b-a363-311cbba9aa4a.png)

Thanks in advance!

**Comment by romangraef** [comment]
the remapJar (which should automatically be built by `build`) should do that. it should have the classifier `-all.jar`

**Comment by tikaros** [comment]
Strangely enough, no... This is the exported class directly from the cloned project. (examplemod-1.0.0-all.jar)
![image](https://user-images.githubusercontent.com/55065837/201610520-b894ff48-33a8-4d6c-a29f-553644dd52ec.png)

Also there is still the class `@Mixin({GuiMainMenu.class})` specified, instead of the encrypted name...
But the `remapJar` task was running when I ran the `build` task
![image](https://user-images.githubusercontent.com/55065837/201611154-772620b2-289d-4329-86d5-1607c328f1a4.png)

**Comment by tikaros** [comment]
But if I want to inject the built Jar into a normal Minecraft Runtime or Optifine, it doesn't work then... With ForgeGradle there is this reobfJar, which replaces the class names and so you can inject it into the runtime without using Forge.

**Comment by romangraef** [comment]
I feel like this is because the jar gets remapped to intermediaries instead of official mappings. You could try using 
 ```kotlin
tasks.remapJar {
	toM.set("official")
}
```
I'm not sure if this would work (or if this is what you want, anyway) and i am also fairly sure that standard forge reobfJar obfuscates to intermediaries by default as well.

**Comment by romangraef** [comment]
Although I am not sure if mixins are able to handle this. This isn't really the environment mixins were designed for and your mixin refmap might still use intermediaries. I'm not gonna look into that, because it's a very nonstandard use case and not really something i can afford to spend too much time on.

**Comment by romangraef** [comment]
Closing as this is not in scope (This is a forge template and this issue pertains to a non Forge and non FML environment)
