### ISSUE TITLE
Error when doing gradle build

### ISSUE THREAD

**Issue by qixuannL** [romangraef/Forge1.8.9Template#8]
PS C:\Users\123\Desktop\1.8.9-master> gradle build

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\123\Desktop\1.8.9-master\build.gradle.kts' line: 1

* What went wrong:
Plugin [id: 'gg.essential.loom', version: '0.10.0.+', artifact: 'gg.essential:architectury-loom:0.10.0.+'] was not found in any of the following sources:

- Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
- Plugin Repositories (dynamic plugin versions are not supported)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 0s

**Comment by romangraef** [comment]
Did you change anything in the settings.gradle.kts? Cause there is a missing repository in that repository list and i cannot repro this in a fresh clone.

**Comment by qixuannL** [comment]
i didn't edited anything on settings

**Comment by romangraef** [comment]
Oh, you are using the wrong gradle version. Please use the gradle wrapper (`gradlew build`) instead of your host gradle.

**Comment by qixuannL** [comment]
worked like a charm, thanks :D
